// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgpa7U6mzvqmDWlJVwAw8XarqRNTSZ-yc',
    appId: '1:296543469981:web:6825d31ecf437c64cdaf74',
    messagingSenderId: '296543469981',
    projectId: 'bank-dokumen',
    authDomain: 'bank-dokumen.firebaseapp.com',
    storageBucket: 'bank-dokumen.firebasestorage.app',
    measurementId: 'G-HKXMKL4KPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWCZBUMOwHonGcRafirqgIuuVMrVyGR0',
    appId: '1:296543469981:android:a8b9e2edd5008a17cdaf74',
    messagingSenderId: '296543469981',
    projectId: 'bank-dokumen',
    storageBucket: 'bank-dokumen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_-IoxGUPoqw8bkpqR-myCK11ZkucJvY',
    appId: '1:296543469981:ios:d8de87cdaa840c40cdaf74',
    messagingSenderId: '296543469981',
    projectId: 'bank-dokumen',
    storageBucket: 'bank-dokumen.firebasestorage.app',
    iosBundleId: 'com.example.bankDokumen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_-IoxGUPoqw8bkpqR-myCK11ZkucJvY',
    appId: '1:296543469981:ios:d8de87cdaa840c40cdaf74',
    messagingSenderId: '296543469981',
    projectId: 'bank-dokumen',
    storageBucket: 'bank-dokumen.firebasestorage.app',
    iosBundleId: 'com.example.bankDokumen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgpa7U6mzvqmDWlJVwAw8XarqRNTSZ-yc',
    appId: '1:296543469981:web:ce390a4ce56f9014cdaf74',
    messagingSenderId: '296543469981',
    projectId: 'bank-dokumen',
    authDomain: 'bank-dokumen.firebaseapp.com',
    storageBucket: 'bank-dokumen.firebasestorage.app',
    measurementId: 'G-G2P2P2VLQ7',
  );
}
